package com.couchbase.cblite.enums;

public enum ResultCode {
    SUCCESS,
    ERROR,
    DATABASE_DOES_NOT_EXIST,
    MISSING_DOCUMENT_PARAM,
    DATABASE_ALREADY_EXISTS,
    EMPTY_IMAGE_DATA,
    EMPTY_OR_INVALID_IMAGE_DATA,
    MISSING_PARAM,
    DOCUMENT_DOES_NOT_EXIST,
    JSON_ERROR,
    CHANGE_LISTENER_DOES_NOT_EXISTS,
    CHANGE_LISTENER_ALREADY_EXISTS,
    INVALID_DB_NAME,
    REPLICATOR_LISTENER_ALREADY_EXISTS,
    REPLICATOR_LISTENER_DOES_NOT_EXISTS,
    COULD_NOT_CREATE_QUERY,
    QUERY_LISTENER_ALREADY_EXISTS,
    QUERY_LISTENER_DOES_NOT_EXIST,
    DATABASE_OR_QUERY_RESOURCE_DOES_NOT_EXIST,
    REPLICATOR_DOES_NOT_EXIST,
    QUERY_RESOURCE_DOES_NOT_EXIST,INVALID_QUERY;

}

