package cordova.plugin.couchbaselite.enums;

public enum ResultCode { SUCCESS, EXIST, ERROR, DATABASE_DOES_NOT_EXIST, MISSING_DOCUMENT_PARAM, DATABASE_ALREADY_EXISTS, CONTENT_TYPE_DOES_NOT_EXIST, EMPTY_IMAGE_DATA }

