package com.couchbase.cblite.enums;

public enum ResultCode {
    SUCCESS,
    EXIST,
    ERROR,
    DATABASE_DOES_NOT_EXIST,
    MISSING_DOCUMENT_PARAM,
    DATABASE_ALREADY_EXISTS,
    EMPTY_IMAGE_DATA,
    EMPTY_OR_INVALID_IMAGE_DATA,
    MISSING_PARAM,
    DOCUMENT_DOES_NOT_EXIST
}

